# Generated by Django 5.1 on 2025-01-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0002_conta_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField()),
                ('tipo', models.CharField(max_length=1)),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Movimentaçõe',
            },
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda'},
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
