# Generated by Django 5.1 on 2025-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0003_movimentacao_alter_venda_options_conta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='agencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='instituicao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='numero_conta',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
